[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.24"
optimizer = true
optimizer_runs = 200
via_ir = false
ffi = true
fs_permissions = [{ access = "read", path = "./broadcast" }]

# Remappings
remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "@chainlink/contracts/=lib/chainlink-brownie-contracts/contracts/",
    "@foundry-devops/=lib/foundry-devops/src/",
]

[profile.default.fuzz]
runs = 1000

[profile.default.invariant]
runs = 500
depth = 50
