[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.24"
optimizer = true
optimizer_runs = 200
via_ir = false
ffi = false

# Remappings
remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "@chainlink/contracts/=lib/chainlink-brownie-contracts/contracts/",
]

[profile.default.fuzz]
runs = 1000

[profile.default.invariant]
runs = 500
depth = 50
